# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff6a204194ac29b2bd64d7f33de46c5733a1d3e452c3fa621cbf06344801f4ef188bffbd2f9bbe9bfaa666d02d8056f65fb2c21ea407f321fa2a641bc36a4ab3

test:
  secret_key_base: face5dff302b22fcd0d8bce72b027c08fcdc537a34f05099e7466f17b37f4ea398ffdc106039d5d7e6d7d30b1dc39f4b6b50441e6fb346fc40d8ad78625479d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
